# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules

windowrule = match:class plugdata, float on
windowrule = match:title Paramètres Steam, float on
windowrule = match:class REAPER, rounding 0
windowrule = match:class zenity, center on
