[qt]
KDE\contrast=4
KWinPalette\activeBackground=#eedfe3
KWinPalette\activeBlend=#e3e5e7
KWinPalette\activeForeground=#21191d
KWinPalette\activeTitleBtnBg=#f6e7eb
KWinPalette\frame=#f6e7eb
KWinPalette\inactiveBackground=#f7d3e1
KWinPalette\inactiveBlend=#eff0f1
KWinPalette\inactiveForeground=#504348
KWinPalette\inactiveFrame=#f6e7eb
KWinPalette\inactiveTitleBtnBg=#f6e7eb
Palette\active=#504348, #f1e1e6, #ffffff, #f9f0f2, #d4678d, #e6b8c5, #21191d, #ffffff, #21191d, #fff8f8, #f6e7eb, #76334c, #884b6a, #ffffff, #006496, #9900cf, #f6e7eb, #000000, #f6e7eb, #21191d, #7f7176, #884b6a
Palette\disabled=#8a6f77, #f6e7eb, #ffffff, #f9f0f2, #d4678d, #e6b8c5, #6f5f64, #ffffff, #6f5f64, #f6e7eb, #f6e7eb, #76334c, #f6e7eb, #8a6f77, #75899b, #c65dd1, #f6e7eb, #000000, #f6e7eb, #21191d, #b08f99, #f6e7eb
Palette\inactive=#504348, #f1e1e6, #ffffff, #f9f0f2, #d4678d, #e6b8c5, #21191d, #ffffff, #21191d, #fff8f8, #f6e7eb, #76334c, #d5c1ca, #504348, #006496, #9900cf, #f6e7eb, #000000, #f6e7eb, #21191d, #7f7176, #d5c1ca
