
credit = Made by Untwinxer: https://untwinxer.com

[All]
primary = 230, 0, 69
secondary = 72, 21, 39
selection = 153, 0, 53
text = 255, 255, 255
background = 0, 0, 0
background_secondary = 12, 13, 14

# All colors below are optional. If removed from this file they will inherit
# from the colors above.

tooltip = 12, 13, 14
tooltip_accent = 72, 21, 39
tooltip_text = 255, 255, 255
quad_guides = 230, 0, 69
error = 230, 0, 69
warning = 230, 0, 69
record_icon = 230, 0, 69

[Spectrum]
primary = 255, 255, 255
secondary = 230, 0, 69
frequency_lines = 86, 96, 111
refrence_line = 172, 192, 222
threshold_line = 172, 192, 222

[Oscilloscope]
primary = 230, 0, 69
secondary = 86, 96, 111
a_button = 255, 127, 127
b_button = 127, 255, 127
c_button = 102, 102, 255
d_button = 255, 127, 255
button_text = 255, 255, 255
clip_warning_light = 255, 0, 0

[Waveform]
primary = 230, 0, 69
low_band = 230, 0, 69
mid_band = 102, 90, 255
high_band = 0, 255, 255
history_low_band = 255, 0, 0
history_mid_band = 0, 255, 0
history_high_band = 0, 0, 255

[Stereometer]
primary = 230, 0, 69
guides = 125, 0, 37
low_band = 230, 0, 69
mid_band = 102, 90, 255
high_band = 0, 255, 255

[Spectrogram]
frequency_lines = 86, 96, 111

[Loudness]
primary = 230, 0, 69
text = 0, 0, 0

[VUMeter]
primary = 153, 0, 53
needle = 172, 192, 222
above_zero = 230, 0, 69
